apiVersion: v1
kind: Service
metadata:
  name: events-manager-service
  labels:
    name: events-manager-service
    app: events-manager-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    name: events-manager-pod
    app: events-manager-app